### ISSUE TITLE
issue on signin

### ISSUE THREAD

**Issue by sylvainlap** [keystonejs/keystone-test-project#11]
I cloned the keystone-test-project repo, and when I `npm start` it, I can go on localhost:3000, but a click on "Got it, let's begin" throws a 500 error:

```
GET / 304 20.493 ms
GET /js/application.js 304 0.317 ms
GET /keystone/ 302 0.505 ms
Error thrown for request: /keystone/signin
TypeError: Cannot read property 'id' of undefined
    at SigninRoute (D:\DEV\WORKSPACE\keystone-test-project\node_modules\keystone\admin\server\routes\signin.js:17:16)
    at Layer.handle [as handle_request] (D:\DEV\WORKSPACE\keystone-test-project\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\DEV\WORKSPACE\keystone-test-project\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (D:\DEV\WORKSPACE\keystone-test-project\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\DEV\WORKSPACE\keystone-test-project\node_modules\express\lib\router\layer.js:95:5)
    at D:\DEV\WORKSPACE\keystone-test-project\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (D:\DEV\WORKSPACE\keystone-test-project\node_modules\express\lib\router\index.js:330:12)
    at next (D:\DEV\WORKSPACE\keystone-test-project\node_modules\express\lib\router\index.js:271:10)
    at next (D:\DEV\WORKSPACE\keystone-test-project\node_modules\express\lib\router\route.js:121:14)
    at exports.persist (D:\DEV\WORKSPACE\keystone-test-project\node_modules\keystone\lib\session.js:210:3)
    at Layer.handle [as handle_request] (D:\DEV\WORKSPACE\keystone-test-project\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\DEV\WORKSPACE\keystone-test-project\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (D:\DEV\WORKSPACE\keystone-test-project\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\DEV\WORKSPACE\keystone-test-project\node_modules\express\lib\router\layer.js:95:5)
    at D:\DEV\WORKSPACE\keystone-test-project\node_modules\express\lib\router\index.js:277:22
    at param (D:\DEV\WORKSPACE\keystone-test-project\node_modules\express\lib\router\index.js:349:14)
GET /keystone/signin 500 0.651 ms
```

The error is thown by this line: https://github.com/keystonejs/keystone/blob/master/admin/server/routes/signin.js#L17

**Comment by JedWatson** [comment]
Pretty sure this has been resolved. Please re-open if you can still replicate the issue. Thanks!
