### ISSUE TITLE
Mongo error starting test project

### ISSUE THREAD

**Issue by nifl** [keystonejs/keystone-test-project#2]
Following the "Complete Getting Started Guide" detailed at https://github.com/keystonejs/keystone/issues/1612, I receive an error when starting the test project. Mongod is running and otherwise working.
### npm

```
$ KEYSTONE_DEV=true npm start

> keystone-test@1.0.0 start /Users/nifl/Projects/Web/keystone-sites/keystone-test-project
> node keystone.js

------------------------------------------------
Mongo Error:

{ [MongoError: getaddrinfo ENOTFOUND undefined undefined:27017]
  name: 'MongoError',
  message: 'getaddrinfo ENOTFOUND undefined undefined:27017' }
Error: KeystoneJS (Keystone Test) failed to start - Check that you are running `mongod` in a separate process.
    at NativeConnection.<anonymous> (/Users/nifl/Projects/Web/keystone-sites/keystone/lib/core/openDatabaseConnection.js:48:10)
    at emitOne (events.js:77:13)
    at NativeConnection.emit (events.js:169:7)
    at NativeConnection.Connection.error (/Users/nifl/Projects/Web/keystone-sites/keystone/node_modules/mongoose/lib/connection.js:425:8)
    at /Users/nifl/Projects/Web/keystone-sites/keystone/node_modules/mongoose/lib/connection.js:452:14
    at /Users/nifl/Projects/Web/keystone-sites/keystone/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:52:21
    at /Users/nifl/Projects/Web/keystone-sites/keystone/node_modules/mongodb/lib/db.js:226:14
    at null.<anonymous> (/Users/nifl/Projects/Web/keystone-sites/keystone/node_modules/mongodb/lib/server.js:233:9)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at null.<anonymous> (/Users/nifl/Projects/Web/keystone-sites/keystone/node_modules/mongodb-core/lib/topologies/server.js:263:68)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at null.<anonymous> (/Users/nifl/Projects/Web/keystone-sites/keystone/node_modules/mongodb-core/lib/connection/pool.js:77:12)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Socket.<anonymous> (/Users/nifl/Projects/Web/keystone-sites/keystone/node_modules/mongodb-core/lib/connection/connection.js:121:49)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! keystone-test@1.0.0 start: `node keystone.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keystone-test@1.0.0 start script 'node keystone.js'.
npm ERR! This is most likely a problem with the keystone-test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node keystone.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls keystone-test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nifl/Projects/Web/keystone-sites/keystone-test-project/npm-debug.log
```
### mongod:

```
$ mongod
2015-11-02T22:48:52.399-0800 I JOURNAL  [initandlisten] journal dir=/data/db/journal
2015-11-02T22:48:52.400-0800 I JOURNAL  [initandlisten] recover : no journal files present, no recovery needed
2015-11-02T22:48:52.414-0800 I JOURNAL  [durability] Durability thread started
2015-11-02T22:48:52.414-0800 I CONTROL  [initandlisten] MongoDB starting : pid=33631 port=27017 dbpath=/data/db 64-bit host=Forge.local
2015-11-02T22:48:52.414-0800 I CONTROL  [initandlisten] db version v3.0.7
2015-11-02T22:48:52.414-0800 I JOURNAL  [journal writer] Journal writer thread started
2015-11-02T22:48:52.414-0800 I CONTROL  [initandlisten] git version: nogitversion
2015-11-02T22:48:52.414-0800 I CONTROL  [initandlisten] build info: Darwin elcapitanvm.local 15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64 x86_64 BOOST_LIB_VERSION=1_49
2015-11-02T22:48:52.414-0800 I CONTROL  [initandlisten] allocator: system
2015-11-02T22:48:52.414-0800 I CONTROL  [initandlisten] options: {}
2015-11-02T22:48:52.444-0800 I NETWORK  [initandlisten] waiting for connections on port 27017
```

**Comment by tryzf** [comment]
我也遇到这个问题，不知道楼主解决了没有

**Comment by JedWatson** [comment]
Pretty sure this has been resolved. Please re-open if you can still replicate the issue. Thanks!
